spring: 
   application: 
            name: licensing-service
   profiles:
        active: dev

   config:
     import: configserver:http://localhost:8071

#   cloud: config:uri: http://localhost:8071

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"

